
CFLAGS := -Wall
source_directories := ./
binary_directory := ../bin

include make_module_c.mk

sources = main1.c test.c
target = $(binary_directory)/main1
$(eval $(one-exe-rule))

sources = main2.c test.c
target = $(binary_directory)/main2
$(eval $(one-exe-rule))

