
CFLAGS := -Wall
source_directories := ./

include make_module_c.mk

sources = main1.c test.c
target = ../bin/main1
$(eval $(one-exe-rule))

sources = main2.c test.c
target = ../bin/main2
$(eval $(one-exe-rule))

